# frozen_string_literal: true

source "https://rubygems.org"

ruby File.read(".ruby-version").strip

gem "lizarb", github: "rubyonrails-brasil/lizarb"
# gem "lizarb"

group :dev do
  # gems you only want to load if DevSystem is loaded
end
