class MicroSystem::DockerShip < MicroSystem::Ship

  section :helpers

  def self.up(log_level: self.log_level)
    compose("up", log_level:)
  end

  def self.start(log_level: self.log_level)
    compose("start", log_level:)
  end

  def self.stop(log_level: self.log_level)
    compose("stop", log_level:)
  end

  def self.restart(log_level: self.log_level)
    compose("restart", log_level:)
  end

  def self.terminal(service, terminal, terminal_args, menv={})
    dock(menv)

    menv[:ship].terminal(service, terminal, terminal_args)
  end

  def self.docker_directory() = ( temporary_directory )

  section :default

  def self.compose(action, log_level: self.log_level)
    menv = {log_level:}

    dock(menv)

    sh "docker compose -f #{menv[:filename]} #{action}"
  end

  def self.dock(menv)
    menv[:filename] ||= docker_directory.join("docker-compose.#{self.token}.yml").to_s

    log_level menv[:log_level]
    comments = get_comments
    content = get_content(menv)
    content = comments + content
    menv[:content] = content

    FileShell.write_text menv[:filename], content, log_level: :high
    log "Docked #{self} to #{menv[:filename]}"
  end

  def self.get_content(menv)
    ship_menv = {log_level: menv[:log_level]}
    self.call(ship_menv)
    menv[:ship] = ship_menv[:ship]
    services = ship_menv[:services]
    services.each_value { _1.inject_shared_network cl.shared_network } if cl.shared_network
    services = ship_menv[:services].map { [_1.to_s, _2.result] }.to_h
    content = {"services" => services}
    content["networks"] = {cl.shared_network => {"external" => true}} if cl.shared_network

    Kernel.require "yaml"
    YAML.dump content
  end

  def self.call(menv)
    super

    ship = menv[:ship] ||= new
    ship.call(menv)
  end

  def call(menv)
    super

    before

    used_dockerfiles = menv[:used_dockerfiles] ||= cl.used_dockerfiles
    dockerfiles = menv[:dockerfiles] = {}
    used_dockerfiles.each do |name, used_dockerfile|
      log "Processing #{cl} #{name}.dockerfile"
      ship_class, defined_block, used_block = used_dockerfile
      dockerfile = dockerfiles[name] = Dockerfile.new(self, name, defined_block, used_block)
      FileShell.write_text dockerfile.path, dockerfile.content, log_level: :high
      log "Created Dockerfile for #{cl} #{name.inspect} at #{dockerfile.path}"
    end
    logc "#{dockerfiles.size} Dockerfiles used!"

    used_services = menv[:used_services] ||= cl.used_services
    services = menv[:services] = {}
    used_services.each do |name, used_service|
      service_class, name, supername, defined_block, used_block = used_service

      logc "Processing #{cl} #{name} service from #{supername}"
      service = services[name] = service_class.new(self, name, supername)
      service.process(defined_block, used_block)
    end
    logc "#{services.size} Services used!"

    after
  end

  def self.get_comments
    content = FileShell.read_text self.source_location_path, log_level: :higher
    Kernel.require "digest/md5"
    md5 = Digest::MD5.hexdigest content
    path = self.source_location_path.sub App.root.to_s, ""
    <<~YAML
      # DO NOT EDIT THIS FILE MANUALLY - THIS FILE WAS AUTO-GENERATED
      #
      # This docker-compose.yml was generated from service definitions in:
      #   #{path} (#{self})
      #
      # MD5: #{md5}
      #
      # To regenerate this file, run:
      #   liza ship:compose
      #
      # To run the services defined here:
      #   docker compose up
      #
      # To run and stop services using detached mode:
      #   docker compose up -d
      #   docker compose down
    YAML
  end

  section :networks

  def self.shared_network(name=nil)
    return @shared_network if name.nil?
    @shared_network = name.to_s
  end

  def self.create_network(log_level: self.log_level)
    return log(stick :b, cl.system.color, "NO NETWORK FOUND") if shared_network.nil?

    log :higher, (stick :b, cl.system.color, "Creating network for #{self}")
    sh "docker network create #{shared_network}"
  end

  section :services

  def self.defined_services
    fetch(:defined_services) { {} }
  end

  def self.used_services
    @used_services ||= {}
  end

  class Service
    attr_reader :ship, :name, :supername, :result

    def initialize(ship, name, supername)
      @result = {}
      @ship = ship
      @name = name
      @supername = supername
      container_name "#{App.full_name}_#{name}"
    end

    def inject_shared_network(network)
      return if network.nil?
      result["networks"] ||= []
      result["networks"] << network unless result["networks"].include? network
    end

    def process(defined_block, used_block)
      instance_eval(&defined_block) if defined_block
      instance_eval(&used_block) if used_block
      process_persisted_volume
      process_default_port
    end

    def process_persisted_volume
      volumes "./data/#{App.mode}/micro_ships/#{name}:#{persisted}" if persisted
    end

    def process_default_port
      port default_port unless result.key?("ports")
    end

    # properties

    def container_name(string)
      result["container_name"] = string
    end

    def image(string)
      raise "Image not allowed. Build already set to #{result['build']}" if result.key? 'build' 
      raise "Image not allowed. Image already set to #{result['image']}" if result.key? 'image'
      result["image"] = string
    end

    def build_dockerfile(key)
      raise "Block not allowed here" if block_given?
      h = ship.menv[:dockerfiles]
      raise "Dockerfiles #{h.keys.inspect} available, but #{key.inspect} requested" unless h.key? key
      raise "Build not allowed. Build already set to #{result['build']}" if result.key? 'build'
      raise "Build not allowed. Image already set to #{result['image']}" if result.key? 'image'
      result['build'] = {}
      result['build']["context"] = "."
      result['build']["dockerfile"] = h[key].path.to_s
    end

    def build_entrypoint(strings)
      raise "Block not allowed here" if block_given?
      raise "Build not allowed. Build already set to #{result['build']}" if result.key? 'build'
      raise "Build not allowed. Image already set to #{result['image']}" if result.key? 'image'
      result['build'] = {}
      result['build']["context"] = "."
      result['build']["entrypoint"] = strings.to_s
    end

    def command(string)
      result["command"] = string
    end

    def working_dir(string)
      result["working_dir"] = string
    end

    def default_port(number=nil)
      if number
        @default_port = number
      else
        @default_port
      end
    end

    def port(host_port, container_port=default_port)
      raise "not default port" unless default_port
      ports "#{host_port}:#{container_port}"
    end

    def ports(string)
      raise "not default port" unless default_port
      raise "must include ':'" unless string.include? ":"

      result["ports"] ||= []
      result["ports"] << string unless result["ports"].include? string
    end

    def persisted(path = nil, mode: nil)
      if path
        @persisted = path
        @persisted += ":#{mode}" if mode
      else
        @persisted
      end
    end

    def read_only(path_host, path_container=path_host)
      volumes "#{path_host}:#{path_container}:ro"
    end

    def readonly(path_host, path_container=path_host)
      read_only(path_host, path_container)
    end

    def volume(key, container_path, mode: nil)
      host_path = ship.volume_for(name, key).to_s
      host_path += ":#{mode}" if mode

      volumes "#{host_path}:#{container_path}"
    end

    def volumes(string)
      raise "must include ':'" unless string.include? ":"
      result["volumes"] ||= []
      result["volumes"] << string unless result["volumes"].include? string
    end

    def environment(hash)
      hash = hash.map {|k, v| [k.to_s, v.to_s] }.to_h
      result["environment"] ||= {}
      result["environment"].merge! hash
    end

    # TODO: support condition
    # depends_on:
    #   rocketchat_mongodb:
    #     condition: service_healthy
    def depends_on(*services)
      raise "At least one dependency required" if services.empty?
      unless services.all? { |s| s.is_a?(Symbol) || s.is_a?(String) }
        raise "Dependencies must be symbols or strings"
      end
      result["depends_on"] = services.map(&:to_s)
    end

    def restart(value)
      allowed = 
      {
        no:             "no",
        always:         "always",
        on_failure:     "on-failure",
        unless_stopped: "unless-stopped"
      }

      key = value.to_sym
      raise "#{value.inspect} not in #{allowed.keys.inspect}" unless allowed.key?(key)

      result["restart"] = allowed[key]
    end

    def set_value(key, value)
      result[key.to_s] = value
    end

    def add_value(key, value)
      result[key.to_s] ||= []
      result[key.to_s] << value
    end

    def terminals() = ( @terminals ||= {} )

    def terminal(terminal_key, callable=nil, must_be_running: false, &block)
      raise "Must provide a block or a callable object" if callable.nil? && block.nil?
      raise "Cannot provide both a callable object and a block" if callable && block
      callable ||= block
      terminals[terminal_key] = Terminal.new(terminal_key, callable, must_be_running)
    end

  end

  def self.define_service_class(name) = (const_set name.to_s.camelcase, Class.new(Service))

  def self.define_service(name, class: Service, &block)
    service_class = binding.local_variable_get(:class)
    log :highest, "defining #{name.inspect} as a #{service_class}"
    defined_services[name] = [service_class, name, name, block]
  end

  def self.use_service(supername, name=supername, ship: self, class: Service, &block)
    service_class = binding.local_variable_get(:class)
    ship_class = ship
    ship_class = Liza.find_controller :ship, ship_class if ship_class.is_a?(Symbol)

    defined_service = ship_class.defined_services[supername]
    defined_service_class, defined_name, _defined_supername, defined_block = defined_service

    used_services[name] = [defined_service_class, name, defined_name, defined_block, block]
  end

  define_service :empty

  section :terminal

  class Terminal
    attr_reader :key, :callable

    def initialize(key, callable, must_be_running)
      @key = key
      @callable = callable
      @must_be_running = must_be_running
    end

    def call(args) = ( callable.call(args) )

    def must_be_running?() = ( @must_be_running )
  end

  def terminal(service_key, terminal_key, terminal_args)
    services = menv[:services]
    service = services[service_key.to_sym]
    raise "Service #{service_key} not found in #{services.keys.inspect}" unless service
    terminal = service.terminals[terminal_key.to_sym]
    raise "Terminal #{terminal_key} not found in #{service.terminals.keys.inspect}" unless terminal

    logc "Calling #{cl} #{service_key}/#{terminal_key} with args #{terminal_args.inspect}"
    raise "Terminal #{terminal_key} must be running, but service #{service_key} is not running" if terminal.must_be_running? && !is_service_running(service)

    container_name = service.result['container_name']
    command_line = terminal.call(terminal_args)
    sh "docker exec -it #{container_name} #{command_line}"
  end

  def is_service_running(service)
    container_name = service.result['container_name']
    sh "docker ps --filter name=#{container_name} --filter status=running --format '{{.Names}}' | grep -w #{container_name}"
  end

  section :dockerfiles

  def self.defined_dockerfiles() = ( fetch(:defined_dockerfiles) { {} } )

  def self.used_dockerfiles() = ( @used_dockerfiles ||= {} )

  def self.dockerfile(name, class: Dockerfile, &block)
    define_dockerfile(name, class:, &block)
    use_dockerfile(name)
  end

  def self.define_dockerfile(name, class: Dockerfile, &block)
    dockerfile_class = binding.local_variable_get(:class)
    raise "Dockerfile #{name.inspect} already defined in #{self}" if defined_dockerfiles.key? name
    log :highest, "defining #{name.inspect} as a #{dockerfile_class}"
    defined_dockerfiles[name] = block
  end

  def self.use_dockerfile(name, ship: self, &block)
    ship_class = ship
    ship_class = Liza.find_controller :ship, ship_class if ship_class.is_a?(Symbol)
    raise "Dockerfile #{name.inspect} not defined in #{ship_class}" unless ship_class.defined_dockerfiles.key? name

    defined_block = ship_class.defined_dockerfiles[name]
    used_dockerfiles[name] = [ship_class, defined_block, block]
  end

  class Dockerfile
    def initialize(ship, name, defined_block, used_block)
      @ship = ship
      @name = name
      @lines = []
      line "# DO NOT EDIT THIS FILE MANUALLY - THIS FILE WAS AUTO-GENERATED"
      line "# SOURCE: #{ship.cl.source_location_path}"

      instance_eval(&defined_block) if defined_block
      instance_eval(&used_block) if used_block
    end

    def path() = ( @path ||= @ship.cl.docker_directory.join("#{name}.dockerfile") )

    def content() = ( lines.map { (_1.is_a? Symbol) ? "# MARK #{_1}" : _1 }.join("\n") )

    attr_reader :name, :lines

    def from_dockerfile(key)
      h = @ship.menv[:dockerfiles]
      raise "Dockerfiles #{h.keys.inspect} available, but #{key.inspect} requested" unless h.key? key

      d = h[key]
      d.lines.each { line _1 unless _1 == ""}
      line_blank
      line_mark :"from_#{key}"
      line "FROM #{key}"
    end

    def line(string) = ( raise ArgumentError, "string must be a String" unless string.is_a? String ; lines << string )

    def line_blank() = ( lines << "" )

    def line_mark(mark) = ( raise ArgumentError, "mark must be a Symbol" unless mark.is_a? Symbol ; lines << mark )

    def line_before(mark, string)
      index = lines.index(mark)
      raise "mark #{mark.inspect} not found in Dockerfile #{name.inspect}" unless index
      lines.insert(index, string)
    end

    def line_after(mark, string)
      index = lines.index(mark)
      raise "mark #{mark.inspect} not found in Dockerfile #{name.inspect}" unless index
      lines.insert(index + 1, string)
    end

    def line_from(image_or_dockerfile_key, key = nil)
      key = image_or_dockerfile_key if key.nil? && image_or_dockerfile_key.is_a?(Symbol)
      s = "FROM #{image_or_dockerfile_key}"
      s = "#{s} AS #{image_or_dockerfile_key}" if key
      line s
    end

  end

  section :instance_hooks

  def before; end

  def after; end

  section :instance_helpers

  def volume_for(name, key)
    cl.data_directory.join("volume_#{name}_#{key}")
  end

end
