#!/usr/bin/env ruby

# global executable liza forwards to local executable when in a mother project directory
path = "#{Dir.pwd}/exe/lizarb"
path = "#{__dir__}/lizarb" unless File.exist? path
Kernel.load path
