#!/usr/bin/env ruby

$APP = ENV["APP"]

$VERBOSE = ENV["VERBOSE"]

$LOAD_PATH.unshift "#{Dir.pwd}/lib"

require_relative "../lib/lizarb.rb"

Lizarb.setup

Lizarb.app

Lizarb.call

App.call ARGV

Lizarb.exit
